# Generated by Django 4.1.5 on 2023-01-20 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_profile_diner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='diner',
            name='user',
        ),
        migrations.AddField(
            model_name='diner',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diner',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diner',
            name='phone',
            field=models.TextField(null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Must have strictly 10 digits'), django.core.validators.MaxLengthValidator(10, 'Must have strictly 10 digits')]),
        ),
        migrations.AddField(
            model_name='diner',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
