# Generated by Django 4.1.5 on 2023-01-20 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_diner_name_remove_diner_user_diner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diner',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Must have strictly 10 digits')]),
        ),
    ]
