# Generated by Django 4.1.5 on 2023-01-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
