# Generated by Django 4.1.5 on 2023-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
