# Generated by Django 4.1.5 on 2023-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_layout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
