# Generated by Django 4.1.5 on 2023-01-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_layout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='numCols',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='numRows',
            field=models.IntegerField(null=True),
        ),
    ]
