# Generated by Django 4.1.5 on 2023-01-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_layout_numcols_layout_numrows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='numCols',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='numRows',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menudata', models.CharField(max_length=1000)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.manager')),
            ],
        ),
    ]
